name: Setup and Test
description: Setup environments and run tests

runs:
  using: composite
  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
      with:
        node-version-file: .node-version
        cache: pnpm

    - name: Install Dependencies
      shell: bash
      run: pnpm i

    - name: Install Playwright Browsers
      shell: bash
      run: pnpm -s playwright install --with-deps

    - name: Run tests
      shell: bash
      run: pnpm -s test
