name: Setup and Test
description: Setup environments and run tests

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .node-version

    - name: Install Dependencies
      shell: bash
      run: npm ci

    - name: Install Playwright Browsers
      shell: bash
      run: npx playwright install --with-deps

    - name: Run tests
      shell: bash
      run: npm run test
