name: Preview Release

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  preview-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup and Test
        uses: ./.github/actions/setup-and-test

      - name: Bump Version
        run: pnpm -s changeset version

      - name: Build
        run: pnpm -s prepublishOnly

      - name: Publish Preview Release
        run: pnpx pkg-pr-new publish --compact
